Models/Pessoa.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Sample.Models
{
    public class Pessoa
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Cpf { get; set; }
        public DateTime DtNascimento { get; set; }

        public virtual IList<Endereco> Endereco {get; set; }
        
        //public void AlterarCliente()
        //{


        //}

        //public void IncluirCliente()
        //{


        //}

        //public void ExcluirCliente()
        //{


        //}

        //public void ConsultarCliente()
        //{


        //}
    }
}

Controllers/Pessoa/PessoaController.cs
using Sample.Controllers.Base;
using Sample.Filters;
using Sample.Infra.Repository.Interfaces;
using Sample.Infra.Data;
using Sample.Infra.Repository;
using Sample.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Sample.Controllers
{
    [Authorize]//[Authorize(Roles = "Administrador")]
    public class PessoaController : BaseController
    {
        IPessoaRepository pessoaRepository;

        public PessoaController()
        {
            pessoaRepository = new PessoaRepository();
        }

        public PessoaController(IPessoaRepository repository)
        {
            this.pessoaRepository = repository;
        }

        public ActionResult Index()
        {
            IEnumerable<Pessoa> result = pessoaRepository.GetAll();
            return View(result);
        }

        [LogAction]
        public ActionResult Edit(int id)
        {
            Pessoa pessoa = pessoaRepository.GetById(id);

            //var perfil = Roles.GetRolesForUser(user.UserName).FirstOrDefault();

           // user.Perfil = perfil;

            if (pessoa == null)
                return HttpNotFound();
            return View(pessoa);

        }

        [LogAction]
        [HttpPost]
        public ActionResult Edit(Pessoa model)
        {
            if (!ModelState.IsValid)
                return Edit(model.Id);

            this.pessoaRepository.Update(model);
            
            ViewBag.Success = "Operacao Realizada com Sucesso";

            IEnumerable<Pessoa> result = this.pessoaRepository.GetAll();

            return View("Index", result);
        }

        [HttpDelete]
        public ActionResult Remove(int id)
        {
            var pessoa = this.pessoaRepository.GetById(id);

            if (pessoa == null)
                return HttpNotFound();
                     

            this.pessoaRepository.Delete(pessoa);

            return Json("OK");
        }

        public ActionResult New()
        {
            return View();
        }

        [HttpPost]
        public ActionResult New(Pessoa model)
        {
            if (!ModelState.IsValid)
                return New();

            this.pessoaRepository.Insert(model);

            ViewBag.Success = "Operacao Realizada com Sucesso";

            IEnumerable<Pessoa> result = this.pessoaRepository.GetAll();

            return View("Index", result);
        }

    

    }
}

Views/Pessoa/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

@model Sample.Models.Pessoa

<div class="page-header">

    <h2>Detalhe de Pessoa</h2>

</div>

@using (Html.BeginForm("Edit", "Pessoa", FormMethod.Post, new { @class = "form-horizontal" }))
{

    <div class="form-group">
        @Html.LabelFor(x => x.Nome, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.Nome, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Nome)
        </div>
    </div>
       
    <div class="form-group">
        @Html.LabelFor(x => x.Email, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Email)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Cpf, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.Cpf, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Cpf)
        </div>
    </div>
    
     <div class="form-group">
        @Html.LabelFor(x => x.DtNascimento, new { @class = "col-sm-2 control-label" })
         <div class="col-sm-10">       
            @Html.TextBoxFor(x => x.DtNascimento, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.DtNascimento)
        </div>
    </div>
    
    <div class="form-group">
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default btn-success">Alterar Cliente</button>
            </div>
        </div>
    </div>


}

Views/Pessoa/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model IEnumerable<Sample.Models.Pessoa>

@section scripts 
    {
        <script type="text/javascript">
            $(document).ready(function () {
                $("a#lnkExcluir").click(function (e) {
                    var id = $(this).attr("data-id");
                    e.preventDefault();
                    $("#modalConfirmation").modal("show");
                    $("#btnConfirmarExclusao").attr("data-id", id);
                })
                $("#btnConfirmarExclusao").click(function () {
                    var id = $(this).attr("data-id");

                    $.ajax({
                        url: "/Pessoa/Remove",
                        contentType: "application/json",
                        data: JSON.stringify({ id: id }),
                        type: "DELETE",
                        success: function () {
                            $("#modalConfirmation").modal("hide");
                            $("a#lnkExcluir[data-id='" + id + "']").closest("tr").fadeOut("slow");
                        }
                    });
                });
            });
        </script>
    }

<div class="page-header">
    <header>Administracao de Cliente</header>
</div>

<article>

    @if (ViewBag.Success != null)
    { 
        <div class="alert alert-success" role="alert">@ViewBag.Success</div>
    }    
    
    <table class="table tale-striped table-bordered">

        <thead>
            <tr>
                <th>Id</th>
                <th>Nome</th>                
                <th>Email</th>
                <th>CPF</th>
                <th>Data de Nascimento</th>                
                <th>Acoes de Pessoa</th> 
                <th>Endereco</th> 
            </tr>
        </thead>

        <tbody>
            @foreach (var pessoa in Model)
            {
                <tr>
                    <td>@pessoa.Id</td>
                    <td>@pessoa.Nome</td>
                    <td>@pessoa.Email</td>
                    <td>@pessoa.Cpf</td>
                    <td>@pessoa.DtNascimento.ToString("dd/MM/yyyy")</td>
                    <td>
                        @Html.ActionLink("Editar", "Edit", new {id = pessoa.Id})
                        @Html.ActionLink("Excluir", "Remove", new { id = pessoa.Id }, new { id = "lnkExcluir", data_id = pessoa.Id })
                    </td>
                    <td>@Html.ActionLink("Endereco", "Index", "Endereco" ,new {idPessoa = pessoa.Id}, null)</td>
                </tr>
            }
        </tbody>

    </table>

    <div>
        <a href="/Pessoa/New" class="btn btn-primary btn-success pull-right" role="button">Criar Novo Cliente</a>
    </div>

</article>

<!-- Modal -->
<div class="modal fade" id="modalConfirmation" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Confirmação de Exclusão</h4>
      </div>
      <div class="modal-body">
        Deseja realemnte excluir o Cliente ?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-danger" id="btnConfirmarExclusao">Confirmar</button>
      </div>
    </div>
  </div>
</div>

Views/Pessoa/New.cshtml
@{
    ViewBag.Title = "New";
    Layout = "~/Views/Shared/_Layout.cshtml";
    
    
}



@model Sample.Models.Pessoa

<div class="page-header">
    <h2>Nova Pessoa</h2>
</div>

@using (Html.BeginForm("New", "Pessoa", FormMethod.Post, new { @class = "form-horizontal" }))
{
    <div class="form-group">
        @Html.LabelFor(x => x.Nome, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.Nome, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Nome)
        </div>
    </div>
       
    <div class="form-group">
        @Html.LabelFor(x => x.Email, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Email)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Cpf, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.Cpf, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Cpf)
        </div>
    </div>
    
     <div class="form-group">
        @Html.LabelFor(x => x.DtNascimento, new { @class = "col-sm-2 control-label" })
         <div class="col-sm-10">       
            @Html.TextBoxFor(x => x.DtNascimento, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.DtNascimento)
        </div>
    </div>
    
    <div class="form-group">
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default btn-success">Salvar Cliente</button>
            </div>
        </div>
    </div>
}