Models/Endereco.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Sample.Models
{
    public class Endereco
    {

        public int Id { get; set; }
        public string Logradouro { get; set; }
        public string Bairro { get; set; }
        public string CEP { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string Pais { get; set; }
        public int IdPessoa { get; set; }
       // public TipoEndereco TipoEndereco { get; set; }
    }
}

Controllers/EnderecoController.cs
using Sample.Infra.Repository;
using Sample.Infra.Repository.Interfaces;
using Sample.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sample.Controllers
{
    public class EnderecoController : Controller
    {
        IPessoaRepository pessoaRepository;

        public EnderecoController()
        {
            pessoaRepository = new PessoaRepository();
        }

        public EnderecoController(IPessoaRepository repository)
        {
            this.pessoaRepository = repository;
        }
        //
        // GET: /Endereco/

        public ActionResult Index(int idPessoa)
        {
            Pessoa pessoa = pessoaRepository.GetById(idPessoa);

            return View(pessoa);
        }
        public ActionResult New(int idPessoa)
        {
            ViewBag.IdPessoa = idPessoa;
            return View();
        }

        [HttpPost]
        public ActionResult New(Endereco endereco, int idPessoa)
        {

            Pessoa pessoa = pessoaRepository.GetById(idPessoa);

            pessoa.Endereco.Add(endereco);

            this.pessoaRepository.Update(pessoa);

            ViewBag.Success = "Operacao Realizada com Sucesso";

            return View("Index", pessoa);

        }


    }
}

Views/Endereco/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model Sample.Models.Pessoa

@section scripts 
    {
    <script type="text/javascript">
        $(document).ready(function () {
            $("a#lnkExcluir").click(function (e) {
                var id = $(this).attr("data-id");
                e.preventDefault();
                $("#modalConfirmation").modal("show");
                $("#btnConfirmarExclusao").attr("data-id", id);
            })
            $("#btnConfirmarExclusao").click(function () {
                var id = $(this).attr("data-id");

                $.ajax({
                    url: "/Pessoa/Remove",
                    contentType: "application/json",
                    data: JSON.stringify({ id: id }),
                    type: "DELETE",
                    success: function () {
                        $("#modalConfirmation").modal("hide");
                        $("a#lnkExcluir[data-id='" + id + "']").closest("tr").fadeOut("slow");
                    }
                });
            });
        });
    </script>
}

<div class="page-header">
    <header>Administracao de Cliente</header>
</div>

<article>

    @if (ViewBag.Success != null)
    { 
        <div class="alert alert-success" role="alert">@ViewBag.Success</div>
    }

    <table class="table tale-striped table-bordered">

        <thead>
            <tr>
                <th>Id</th>
                <th>Logradouro</th>
                <th>Bairro</th>
                <th>CEP</th>
                <th>Cidade</th>
                <th>Estado</th>
                <th>Pais</th>
                <th>Acoes de Pessoa</th>


            </tr>
        </thead>

        <tbody>
            @foreach (var endereco in Model.Endereco)
            {
                <tr>
                    <td>@endereco.Id</td>
                    <td>@endereco.Logradouro</td>
                    <td>@endereco.Bairro</td>
                    <td>@endereco.CEP</td>
                    <td>@endereco.Cidade</td>
                    <td>@endereco.Estado</td>
                    <td>@endereco.Pais</td>

                    <td>
                        @Html.ActionLink("Editar", "Edit", new { id = endereco.Id })
                        @Html.ActionLink("Excluir", "Remove", new { id = endereco.Id }, new { id = "lnkExcluir", data_id = endereco.Id })
                    </td>
                    
                </tr>
            }
        </tbody>

    </table>

    <div>
        <a href="/Endereco/New?idPessoa=@Model.Id" class="btn btn-primary btn-success pull-right" role="button">Criar Novo Cliente</a>
    </div>

</article>

<!-- Modal -->
<div class="modal fade" id="modalConfirmation" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Confirmação de Exclusão</h4>
            </div>
            <div class="modal-body">
                Deseja realemnte excluir o Cliente ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-danger" id="btnConfirmarExclusao">Confirmar</button>
            </div>
        </div>
    </div>
</div>

Views/Endereco/New.cshtml
{
    ViewBag.Title = "New";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@model Sample.Models.Endereco

<div class="page-header">
    <h2>Nova Pessoa</h2>
</div>

@using (Html.BeginForm("New", "Endereco", new { idPessoa = ViewBag.IdPessoa }, FormMethod.Post, new { @class = "form-horizontal" }))
{
    <div class="form-group">
        @Html.LabelFor(x => x.Logradouro, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.Logradouro, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Logradouro)
        </div>
    </div>
       
    <div class="form-group">
        @Html.LabelFor(x => x.Bairro, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.Bairro, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Bairro)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.CEP, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.CEP, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.CEP)
        </div>
    </div>
    
     <div class="form-group">
        @Html.LabelFor(x => x.Cidade, new { @class = "col-sm-2 control-label" })
         <div class="col-sm-10">       
            @Html.TextBoxFor(x => x.Cidade, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Cidade)
        </div>
    </div>
    
    <div class="form-group">
        @Html.LabelFor(x => x.Estado, new { @class = "col-sm-2 control-label" })
         <div class="col-sm-10">       
            @Html.TextBoxFor(x => x.Estado, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Estado)
        </div>
    </div>
    
    <div class="form-group">
        @Html.LabelFor(x => x.Pais, new { @class = "col-sm-2 control-label" })
         <div class="col-sm-10">       
            @Html.TextBoxFor(x => x.Pais, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Pais)
        </div>
    </div>
    <div class="form-group">
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default btn-success">Salvar Endereco</button>
            </div>
        </div>
    </div>
}